### ISSUE TITLE
I want the schema to the same as the swagger.json get request

### ISSUE THREAD

**Issue by sinmetal** [favclip/ucon#14]
Since the default, https is set as the schema, it can not distinguish that localhost In http, server in https.

```
{
	"swagger": "2.0",
	"info": {
		"title": "Cloud Platform Training",
		"version": "v1"
	},
	"schemes": [
		"https"
	]
}
```

**Comment by vvakame** [comment]
You can do it in yourself.
check this code. https://github.com/vvakame/ucon-todo/blob/e3f0eadde998e819be90d6f76acfc79f36c9ba4d/api/src/app/main.go#L46-L55
